Algoritmo "MEDIDAS"

Var
       a,b,c : real
Inicio
         escreva("Digite a medida A: ")
         leia(a)
         escreva("Digite a medida B: ")
         leia(b)
         escreva("Digite a medida C: ")
         leia(C)
         escreval("AREA DO QUADRADO = ", a * a)
         escreval("AREA DO TRIANGULO = ", (a * b) / 2)
         escreval("AREA DO TRAPEZIO = ", ((a + b) * c) / 2)
Fimalgoritmo